#
##
### Adicionar repositório Helm
##
#

- name: Adicionar o repositório Helm Traefik
  community.kubernetes.helm_repository:
    name: traefik
    repo_url: https://traefik.github.io/charts
    state: present
    force_update: true


#
##
### Instalar o Kube Prometheus Stack
##
#

- name: Instalar o chart Traefik com redirecionamento automático para HTTPS via YAML
  community.kubernetes.helm:
    name: traefik
    chart_ref: traefik/traefik
    namespace: traefik
    create_namespace: true
    release_state: present
    chart_version: "{{ traefik_helm_chart_version }}"
    values:
      providers:
        kubernetesIngress:
          enabled: true
        kubernetesGateway:
          enabled: true
          experimentalChannel: false
          namespaces: []
          labelselector: ""
          nativeLBByDefault: true
      service:
        enabled: true
        type: LoadBalancer
        spec:
          loadBalancerIP: "{{ traefik_main_gateway_ip }}"
      logs:
        general:
          # -- Alternative logging levels are TRACE, DEBUG, INFO, WARN, ERROR, FATAL, and PANIC.
          level: "INFO"