---
- name: Docker Install
  hosts: all
  vars_files:
    - ../secrets/credentials.yml
  vars:
    ansible_become_password: "{{ become_password }}"
  tasks:

    - name: Update repo
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: Install Dependencies
      become: true
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create keyrings Directory
      become: true
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download GPT keyrings
      become: true
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Alter keyrings/docker.asc permissions
      become: true
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add APT Sources
      become: true
      ansible.builtin.blockinfile:
        path: /etc/apt/sources.list.d/docker.list
        block: |
          deb [arch={{ ansible_architecture | regex_replace('aarch64', 'arm64') }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        create: true
        state: present
        mode: '0644'

    - name: Update repo
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: Install Docker
      become: true
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Add Ansible user to the Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
      become: true
      tags:
        - docker
        - user
