- name: Deploy Long Horn
  hosts: "{{ groups['hybrid'][0] }}"
  vars_files:
    - ../secrets/cluster_values.yml
  tasks:

    #
    ##
    ### Adicionar repositório Helm
    ##
    #

    - name: Adicionar o repositório Helm longhorn
      community.kubernetes.helm_repository:
        name: longhorn
        repo_url: https://charts.longhorn.io
        state: present
        force_update: true

    #
    ##
    ### Instalar o longhorn
    ##
    #

    - name: Instalar o chart longhorn usando Helm
      community.kubernetes.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        namespace: longhorn-system
        create_namespace: true
        release_state: present
        chart_version: "{{ longhorn_chart_version }}"


    - name: Criar Ingress para o Long Horn
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: longhorn-ingress
            namespace: longhorn-system
            annotations:
              kubernetes.io/ingress.class: "nginx"
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
          spec:
            rules:
              - host: "longhorn.{{ domain }}"
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: longhorn-frontend
                          port:
                            number: 80
            tls:
              - hosts:
                - "longhorn.{{ domain }}"
                secretName: longhorn-cert-manager-secret