#
##
### Build da imagem customizada Airflow
##
#

- name: Criar arquivo requirements.txt
  ansible.builtin.copy:
    dest: "./requirements.txt"
    content: |
      apache-airflow-providers-mongo

- name: Criar Dockerfile para a imagem personalizada do Airflow
  ansible.builtin.copy:
    dest: "./Dockerfile"
    content: |
      FROM apache/airflow:latest
      COPY requirements.txt /requirements.txt
      RUN pip install --no-cache-dir -r /requirements.txt

- name: Construir a imagem Docker personalizada do Airflow
  community.docker.docker_image:
    name: "{{ custom_airflow_repo_name }}:latest"
    build:
      path: .
    source: build
    state: present

- name: Fazer login no registro Docker
  community.docker.docker_login:
    registry_url: "{{ docker_registry_url }}"
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"
    reauthorize: yes

- name: Enviar a imagem Docker para o registro
  community.docker.docker_image_push:
    name: "{{ custom_airflow_repo_name }}"
    tag: "latest"

