---
- name: Uninstall K3s and Kube-vip
  hosts: all
  become: true
  vars_files:
    - ../secrets/credentials.yml
    - ../secrets/cluster_values.yml
  tasks:

    #
    ##
    ### Limpeza do ambiente
    ##
    #

    - name: Check if K3s uninstall script exists
      ansible.builtin.stat:
        path: /usr/local/bin/k3s-uninstall.sh
      register: k3s_uninstall_script

    - name: Run K3s uninstall script if it exists
      ansible.builtin.shell: /usr/local/bin/k3s-uninstall.sh
      when: k3s_uninstall_script.stat.exists
      become: true

    - name: Remover o diretório /var/lib/rancher
      ansible.builtin.file:
        path: /var/lib/rancher
        state: absent
      become: true

    - name: Remover o diretório /etc/rancher
      ansible.builtin.file:
        path: /etc/rancher
        state: absent
      become: true

    - name: Encontrar todos os arquivos no diretório ~/.kube/
      ansible.builtin.find:
        paths: /home/{{ ansible_user }}/.kube/
        file_type: file
      register: arquivos_encontrados

    - name: Remover os arquivos encontrados no diretório ~/.kube/
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ arquivos_encontrados.files }}"

    - name: Limpar endereços IP da interface de loopback
      ansible.builtin.command:
        cmd: ip addr flush dev lo
      become: true

    - name: Adicionar endereço IP padrão à interface de loopback
      ansible.builtin.command:
        cmd: ip addr add 127.0.0.1/8 dev lo
      become: true